export const instrumentIDs = [
  // 'mmmususd',
  // 'axpususd',
  // 'aaplususd',
  'baususd',
  'catususd',
  'cvxususd',
  'cscoususd',
  'koususd',
  'xomususd',
  'gsususd',
  'hdususd',
  'ibmususd',
  'intcususd',
  'jnjususd',
  'jpmususd',
  'mcdususd',
  'mrkususd',
  'msftususd',
  'nkeususd',
  'pfeususd',
  'pgususd',
  'trvususd',
  'unhususd',
  'utxususd',
  'vzususd',
  'vususd',
  'wmtususd',
  'wbaususd',
  'disususd',
  // 'diaususd',
  // 'btcusd',
  // 'ethusd',
  // 'eurusd',
]
export const from = '2019-12-29'
export const to = '2020-01-02'
export const timeframe = 'tick'
