export default {
  instrumentIDs: [
    // 'mmmususd',
    // 'axpususd',
    'aaplususd',
    // 'baususd',
    // 'catususd',
    // 'cvxususd',
    // 'cscoususd',
    // 'koususd',
    // 'xomususd',
    // 'gsususd',
    // 'hdususd',
    // 'ibmususd',
    // 'intcususd',
    // 'jnjususd',
    // 'jpmususd',
    // 'mcdususd',
    // 'mrkususd',
    // 'msftususd',
    'nkeususd',
    // 'pfeususd',
    // 'pgususd',
    // 'trvususd',
    // 'unhususd',
    // 'utxususd',
    // 'vzususd',
    // 'vususd',
    // 'wmtususd',
    // 'wbaususd',
    // 'disususd',
    // 'diaususd',
    // 'btcusd',
    // 'ethusd',
    // 'eurusd',
  ],
  fromDate: '2020-03-02',
  toDate: '2020-03-10',
  timeframe: 'tick',
}
