module.exports = {
  instrumentIDs: [
    'mmmususd',
    'axpususd',
    'aaplususd',
    'baususd',
    'catususd',
    'cvxususd',
    'cscoususd',
    'koususd',
    'xomususd',
    'gsususd',
    'hdususd',
    'ibmususd',
    'intcususd',
    'jnjususd',
    'jpmususd',
    'mcdususd',
    'mrkususd',
    'msftususd',
    'nkeususd',
    'pfeususd',
    'pgususd',
    'trvususd',
    'unhususd',
    'utxususd',
    'vzususd',
    'vususd',
    'wmtususd',
    'wbaususd',
    'disususd',
    'diaususd',
    'btcusd',
    'ethusd',
    'eurusd'
  ],
  from: '2020-01-15',
  to: '2020-01-16',
  timeframe: 'tick'
}
